feat: passbolt operator v1.1.0
urbanmedia/passbolt-operator-helm pull request #4
Opened 2023-04-05 21:41 UTC by leonsteinhaeuser

# Description

With this PR the CRD and the deployment files were adapted to the operator version v1.1.0.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Kubernetes version:
- Kubectl version:
- Node operation system:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-04-06 16:15 UTC, jangarcia requested changes
I get the following error when trying to upgrade the `passbolt-operator` release:

> Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "passboltsecrets.passbolt.tagesspiegel.de" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "passbolt-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "passbolt-operator-system"

2023-04-06 16:49 UTC, jangarcia reviewed
This might be outside of the scope of this PR, but `passbolt-secret` Helm chart should also be updated to enable using the new features by updating the `PassboltSecret` api version and perhaps even enabling defining several secrets and their secret type.

2023-04-06 19:54 UTC, leonsteinhaeuser commented on charts/passbolt-operator/README.md
> +```
> I get the following error when trying to upgrade the `passbolt-operator` release:
> 
> > Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "passboltsecrets.passbolt.tagesspiegel.de" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "passbolt-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "passbolt-operator-system"
> 
> After deleting the CRD manually, it works.

Unfortunately, I cannot change the behavior. This guide is intended to help users update their deployments.

2023-04-11 16:17 UTC, jangarcia approved these changes

2023-04-11 16:22 UTC, merged